### ISSUE TITLE
gMessageNotificationBar is no longer defined in window object

### ISSUE THREAD

**Issue by esellier** [jobisoft/tb-remplates#18]
https://github.com/jobisoft/notificationbar-API/blob/c960943f6d5d2721a184994114abb65f474a1d95/notificationbar/implementation.js#L131

As the gMessageNotificationBar property is undefined, the notification will be displayed at the window bottom, instead of message headers view (when of course `properties.placement` is `message`).

**Comment by esellier** [comment]
#19 Fix proposed in pull request

**Comment by esellier** [comment]
#

**Comment by jobisoft** [comment]
This does not seem to be an issue with 128.
